services:
  - type: web
    name: tg-mvp-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app_webhook.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: SMTP_HOST
        value: smtp.sendpulse.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: PUBLIC_URL
        sync: false
